# Generated by Django 6.0.5 on 2026-05-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
