# Generated by Django 6.0.5 on 2026-05-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_comment_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='counter',
        ),
    ]
