# Generated by Django 6.0.5 on 2026-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='parent_task',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(help_text='Title of the subtask', max_length=300),
        ),
    ]
