# Generated by Django 6.0.5 on 2026-06-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_rename_parent_task_subtask_task_alter_subtask_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
