# Generated by Django 6.0.5 on 2026-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_subtask_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('IMPROVEMENT', 'Improvement'), ('TECH_TASK', 'Technical Task'), ('REFACTORING', 'Refactoring'), ('MAINTENANCE', 'Maintenance'), ('TESTING', 'Testing'), ('DOCUMENTATION', 'Documentation')], default='FEATURE', max_length=20),
        ),
    ]
