# Generated by Django 6.0.5 on 2026-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='own_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('IMPROVEMENT', 'Improvement'), ('TECH_TASK', 'Technical Task'), ('REFACTORING', 'Refactoring'), ('MAINTENANCE', 'Maintenance'), ('TESTING', 'Testing'), ('DOCUMENTATION', 'Documentation')], default=None, max_length=20, null=True),
        ),
    ]
